[tool.ruff]
target-version = "py312"
line-length = 120
format.preview = true
lint.select = [
  "ALL",
]
lint.ignore = [
  "COM812",  # conflict with formatter
  "CPY",     # No copyright header
  "D",       # No documentation
  "D203",    # one-blank-line-before-class conflicts with D211
  "D213",    # multi-line-summary-first-line conflicts with D212
  "INP001",  #  no package here
  "ISC001",  # conflict with formatter
  "PLR6301", # no force static
  "S",       # no security concerns
  "T201",    # print is fine
]

lint.isort = { known-first-party = [  ], required-imports = [
  "from __future__ import annotations",
] }
lint.preview = true
